name: Setup Node & Dependencies
description: Checkout, setup Node, and install npm dependencies

inputs:
  node-version:
    description: Node.js version
    default: "20"
  github-token:
    description: GitHub token for GitHub Packages authentication
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        registry-url: https://npm.pkg.github.com
        scope: "@aramiworks"
    - run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}
